---

- hosts: localhost
  connection: ssh
  tasks:
    - name: install web server
      yum: name=httpd state=present

    - name: start httpd
      service: name=httpd state=started

    - name: create a file 
      file: path="/var/www/html/index.html" state=touch
        
    - name: add content
      copy:
        dest: "/var/www/html/index.html"
        content: |
          <h1> hello world..! <h1>

